meta_continua={
 'edc14': {
1 : 'Sí',
2 : 'No',
},
 'edc1': {
1 : 'Sí',
2 : 'No',
},
 'edc15-En la UNAM': {1:'Sí',2:'No'},
 'edc15-En otra institución pública': {1:'Sí',2:'No'},
 'edc15-En otra institución privada': {1:'Sí',2:'No'},
 'edc15-En la empresa o institución dónde trabaja': {1:'Sí',2:'No'},
 'edc15-En una asociación': {1:'Sí',2:'No'},
 'edc15-En internet': {1:'Sí',2:'No'},
 'edc2': {
1 : 'Falta de tiempo',
6 : 'Temas de salud',
5 : 'Discapacidad',
4 : 'Falta de ofertas académicas',
2 : 'Costos',
7 : 'Otro (especifique)',
3 : 'Falta de información',
},
 'edc12a': {
1 : 'Menos de $500',
4 : 'Más de $1,500',
3 : '$1,001 – $1,500',
2 : '$501 – $1,000',
},
 'edc12b': {
1 : 'Menos de $1,000',
2 : '$1,001 – $2,000',
3 : '$2,001 – $3,000',
4 : 'Más de $3,000',
},
 'edc12c': {
1 : 'Menos de $10,000',
2 : '$10,001 – $12,000',
3 : '$12,001 – $14,000',
4 : 'Más de $14,000',
},
 'edc3-Tecnología': {1:'Sí',2:'No'},
 'edc3-Conocimientos relacionados con su carrera': {1:'Sí',2:'No'},
 'edc3-Liderazgo': {1:'Sí',2:'No'},
 'edc3-Gestión de proyectos': {1:'Sí',2:'No'},
 'edc3-Análisis de datos': {1:'Sí',2:'No'},
 'edc3-Otra (especifique)': {1:'Sí',2:'No'},
 'edc5-Otro (especifique)': {1:'Sí',2:'No'},
 'edc5-Herramientas digitales para la docencia': {1:'Sí',2:'No'},
 'edc5-Seguridad, privacidad  y gobernanza digital': {1:'Sí',2:'No'},
 'edc5-Desarrollo de software y web (tecnologías aplicadas)': {1:'Sí',2:'No'},
 'edc5-Datos, gestión y automatización': {1:'Sí',2:'No'},
 'edc5-Ofimática': {1:'Sí',2:'No'},
 'edc4-Otro': {1:'Sí',2:'No'},
 'edc4-Chino': {1:'Sí',2:'No'},
 'edc4-Francés': {1:'Sí',2:'No'},
 'edc4-Inglés': {1:'Sí',2:'No'},
 'edc4-Alemán': {1:'Sí',2:'No'},
 'edc4-No lo requiero': {1:'Sí',2:'No'},
 'edc4-Portugués': {1:'Sí',2:'No'},
 'edc6': {
5 : 'Actividades culturales o recreativas',
4 : 'Investigación o gestión institucional',
3 : 'Emprendimiento o proyectos personales',
6 : 'Otro (especifique)',
2 : 'Docencia o tutoría académica',
1 : 'Actividades laborales profesionales',
},
 'edc8': {
3 : 'Avanzado',
2 : 'Intermedio',
1 : 'Básico',
},
 'edc12d': {
1 : 'Sin costo',
2 : 'Hasta $200',
3 : '$201 – $400',
4 : 'Más de $400',
},
 'edc7': {
1 : 'Presencial',
4 : 'Híbrida',
3 : 'Videoconferencia',
2 : 'En línea',
},
 'edc9': {
1 : 'Becas',
6 : 'Información pertinente',
5 : 'Facilidad para acceder a las instalaciones de la UNAM',
4 : 'Flexibilidad de Tiempo para realizar los cursos',
3 : 'Pagos diferidos',
2 : 'Descuentos',
},
 'edc10': {
1 : 'Sí',
2 : 'No',
},
 'edc11-Correo electrónico': {1:'Sí',2:'No'},
 'edc11-Redes sociales': {1:'Sí',2:'No'},
 'edc11-Página oficial': {1:'Sí',2:'No'},
 'edc11-WhatsApp': {1:'Sí',2:'No'},
}
